### ISSUE TITLE
Regression: annoying "bumps"/scratchy noises at track change

### ISSUE THREAD

**Issue by pms967** [marcoc1712/squeezelite#3]
Regression: annoying "bumps"/scratchy noises at track change when using DSD have re-appeared (problem was solved in a previous version).

**Comment by pms967** [comment]
As a reference, here is a full patch between "my last good version" (from “Play_DSD_decoded_by_Mansr_sox” branch, Feb 12) and the current one here (ouch, quite many changes!)

[last_good_to_1_8_4.patch.zip](https://github.com/marcoc1712/squeezelite-R2/files/809381/last_good_to_1_8_4.patch.zip)

**Comment by marcoc1712** [comment]
The only version with DSD support is Play_DSD_decoded_by_Mansr_sox that is currently in devolpment/beta test.

1_8_4 is the maintenance branch of actual release, nothing rellated to dsd here.
