### ISSUE TITLE
Useless duplicate files in source tree...

### ISSUE THREAD

**Issue by pms967** [marcoc1712/squeezelite#4]
(reported files are *exactly* the same, bit by bit...)

$ fdupes -r .

./include-osx/FLAC/stream_decoder.h     
./include/FLAC/stream_decoder.h

./include-osx/FLAC/ordinals.h
./include/FLAC/ordinals.h

./include-osx/FLAC/all.h
./include/FLAC/all.h

./include-osx/FLAC/callback.h
./include/FLAC/callback.h

./include-osx/FLAC/format.h
./include/FLAC/format.h

./include-osx/FLAC/assert.h
./include/FLAC/assert.h

./include-osx/FLAC/export.h
./include/FLAC/export.h

./include-osx/FLAC/stream_encoder.h
./include/FLAC/stream_encoder.h

./include-osx/FLAC/Makefile.am
./include/FLAC/Makefile.am

./include-osx/FLAC/Makefile.in
./include/FLAC/Makefile.in

./include-osx/FLAC/metadata.h
./include/FLAC/metadata.h

./include-osx/vorbis/vorbisfile.h
./include/vorbis/vorbisfile.h

./include-osx/vorbis/vorbisenc.h
./include/vorbis/vorbisenc.h

./include-osx/vorbis/Makefile.am
./include/vorbis/Makefile.am

./include-osx/vorbis/codec.h
./include/vorbis/codec.h

./include-osx/vorbis/Makefile.in
./include/vorbis/Makefile.in

./include-osx/ogg/os_types.h
./include/ogg/os_types.h

./include-osx/ogg/ogg.h
./include/ogg/ogg.h

./include-osx/ogg/Makefile.am
./include/ogg/Makefile.am

./include-osx/ogg/config_types.h.in
./include/ogg/config_types.h.in

./include-osx/ogg/Makefile.in
./include/ogg/Makefile.in

./scripts/squeezelite-s10-pkg
./scripts/squeezelite-s91-pkg

./.git/logs/refs/heads/Play_DSD_decoded_by_Mansr_sox
./.git/logs/HEAD

./include/mad.h
./include-osx/mad.h

./include/neaacdec.h
./include-osx/neaacdec.h

./include/portaudio.h
./include-osx/portaudio.h

./include/pa_mac_core.h
./include-osx/pa_mac_core.h

**Comment by marcoc1712** [comment]
It's a developer choice, to make things easier to mantain.
