### ISSUE TITLE
Build/Makefile: tries to include "mad" even if it's disabled

### ISSUE THREAD

**Issue by pms967** [marcoc1712/squeezelite#5]
futro squeezelite-R2 # USE="dsd" emerge --ask --verbose media-sound/squeezelite-R2

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    ~] media-sound/squeezelite-R2-1.8.4-r1::MyPlayers  USE="dsd -aac -ffmpeg -flac -mad -mpg123 -pulseaudio -resample -visexport -vorbis" 0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] 

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) media-sound/squeezelite-R2-1.8.4-r1::MyPlayers
 * squeezelite-R2-1.8.4.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                          [ ok ]
>>> Unpacking source...
>>> Source unpacked in /var/tmp/portage/media-sound/squeezelite-R2-1.8.4-r1/work
>>> Preparing source in /var/tmp/portage/media-sound/squeezelite-R2-1.8.4-r1/work/squeezelite-R2-1.8.4 ...
 * Applying squeezelite-R2-1.8.4-gentoo-makefile.patch ...                                                                                                                   [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/media-sound/squeezelite-R2-1.8.4-r1/work/squeezelite-R2-1.8.4 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/media-sound/squeezelite-R2-1.8.4-r1/work/squeezelite-R2-1.8.4 ...
 * dsd support enabled
 * FLAC support disabled; add 'flac' USE flag if you need it
 * Ogg/Vorbis support disabled; add 'vorbis' USE flag if you need it
 * MP3 support disabled; add 'mad' (recommended)
 *   or 'mpg123' USE flag if you need it
 * AAC support disabled; add 'aac' USE flag if you need it
make -j1
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  main.c -c -o main.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  slimproto.c -c -o slimproto.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  buffer.c -c -o buffer.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  stream.c -c -o stream.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  utils.c -c -o utils.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  output.c -c -o output.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  output_alsa.c -c -o output_alsa.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  output_pa.c -c -o output_pa.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  output_stdout.c -c -o output_stdout.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  output_pack.c -c -o output_pack.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  decode.c -c -o decode.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  flac.c -c -o flac.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  pcm.c -c -o pcm.o
cc -march=native -O2 -pipe -DDSD -DSL_NO_FLAC -DSL_NO_OGG -DSL_NO_MAD -DSL_NO_MPG123 -DSL_NO_AAC  mad.c -c -o mad.o
mad.c:23:17: fatal error: mad.h: No such file or directory
 #include <mad.h>
                 ^
compilation terminated.
make: *** [Makefile:82: mad.o] Error 1
 * ERROR: media-sound/squeezelite-R2-1.8.4-r1::MyPlayers failed (compile phase):
 *   emake failed

**Comment by marcoc1712** [comment]
Please contact the ebuild script mantainer or follow instructions in "build instructions.txt".
At build time mad header is required.,
